openapi: 3.0.4
info:
  title: Task tracker log models
  description: Log models for logging services of marketplace
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        task:
          $ref: '#/components/schemas/MkplLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    MkplLogModel:
      title: Модель лога для микросервиса Tasktracker
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
        requestTask:
          $ref: '#/components/schemas/TaskLog'
        requestFilter:
          $ref: '#/components/schemas/TaskFilterLog'
        responseTask:
          $ref: '#/components/schemas/TaskLog'
        responseTasks:
          type: array
          items:
            $ref: '#/components/schemas/TaskLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    TaskLog:
      title: Модель лога для объявления
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        status:
          type: string
        priority:
          type: string
        ownerId:
          type: string
        productId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    TaskFilterLog:
      title: Модель лога фильтра
      properties:
        title:
          type: string
        ownerId:
          type: string
        priority:
          type: string
        status:
          type: string

